### ISSUE TITLE
Could not download ontology file

### ISSUE THREAD

**Issue by eicherj** [medizininformatik-initiative/feasibility-deploy#137]
Hi team,

the container `init-elasticsearch` is aiming to download the ontology file:
https://github.com/medizininformatik-initiative/feasibility-deploy/blob/b666160f84a9a53910a3adc38e6dc7897d9866f7/feasibility-portal/backend/docker-compose.yml#L135

Since we are running the portal in the internal network which is behind a proxy, we have added the following env vars:
```yaml
HTTP_PROXY: <IP:PORT>
HTTPS_PROXY: <IP:PORT>
NO_PROXY: dataportal-elastic
```
Yet, we run into the following error:
![Image](https://github.com/user-attachments/assets/12bed034-3985-479b-a14e-05842f74aaa4)

Do you have any idea, what the problem could be?

Also:
- Is there a specific reason why the ontology file is downloaded for a configured version on the fly? I would assume there is somewhat a dependency between either the `init-elasticsearch` or the `dataportal-elastic` containers and the ontology file version. In that case, it would make sense to enforce the version dependency via integrating the oncology file in the docker container directly.
- If this is not an option, is it or would it be possible to provide the elastic.zip via a mounted volume from the file system? For security reasons and because our proxy is quite restrictive we typically don't allow internet access for the docker network.

Thank you very much!

Greetings from Munich (TUM),
Johanna

**Comment by eicherj** [comment]
Using a mount as suggested by @michael-82 

```
    volumes:
      - type: bind
        source: /home/foo/my-ontology.zip
        target: /tmp/mounted_onto.zip
        read_only: true
```

has solved the issue.

Thank you very much!
